name: Deploy to Vagrant VM

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 192.168.33.10 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Vagrant VM
        run: |
          ssh -v $SSH_USERNAME@192.168.33.10 'echo "hello world" > /home/vagrant/file.txt'
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

