name: Perform on Vagrant VM

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Remote SSH
    runs-on: ubuntu-latest
    
    steps:
    - name: ls -a via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ls -a
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        privateKey: ${{ secrets.KEY}}




   
#    steps:
#    - name: executing remote ssh commands using password
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USER }}
#        key: ${{ secrets.KEY }}
#        port: ${{ secrets.PORT }}
#        script: |
#            whoami
#            ls -al