name: Perform on Vagrant VM

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Remote SSH
    runs-on: ubuntu-latest

    steps:
      - name: Run Commands Remotely
        run: |
          ssh vagrant@192.168.33.45 "echo 'Hello, remote world!'"




   
#    steps:
#    - name: executing remote ssh commands using password
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USER }}
#        key: ${{ secrets.KEY }}
#        port: ${{ secrets.PORT }}
#        script: |
#            whoami
#            ls -al