name: Perform on Vagrant VM

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Remote SSH
    runs-on: ubuntu-latest

    steps:
      - name: Run Commands Remotely
        run: |
          ssh user@hostname "echo 'Hello, remote world!'"