name: Deploy to EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setting up SSH agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Creating file and performing action to EC2 
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.80.56.166 'bash -s' << EOF
        echo "Hello from GitHub Actions....!" > ~/file.txt
        EOF

